### ISSUE TITLE
Struct with the same name as module name

### ISSUE THREAD

**Issue by don1ck** [mapbox/turf-swift#110]
Hi! 
Search sdk team has issue with turf module in our frameworks. 

It is known issue with swift modules, [discussed here](https://bugs.swift.org/browse/SR-898) and [swift bug](https://bugs.swift.org/browse/SR-898).

In short words we are using `BoundingBox` struct which exposed to public interface of a `xcframework`. After the `xcframework` build for distribution all notions of `BoundingBox` becomes `Turf.BoundingBox` which is right (ModuleName.TypeName).
But because Turf module has entity named [Turf](https://github.com/mapbox/turf-swift/blob/master/Sources/Turf/Turf.swift) error occurs  `'BoundingBox' is not a member type of 'Turf'`.

Simple workaround would be to rename `Turf` entity.

**Comment by 1ec5** [comment]
The Turf struct currently only exists because of the static `intersection(_:_:)` method. I think we can safely make that a standalone function.

/cc @Udumft

**Comment by julianrex** [comment]
Noting that I also hit this issue, when enabling `BUILD_LIBRARIES_FOR_DISTRIBUTION` (built with Xcode 11.6 and consuming the binary from an Xcode 12.0 project).
