### ISSUE TITLE
功能不全啊

### ISSUE THREAD

**Issue by fenghedemo1** [mapbox/turf-swift#117]
什么时候能把支持安卓的api都迁移到swift上啊? 为什么swift的api这么少

**Comment by 1ec5** [comment]
(Google Translate)

> When can I migrate all the APIs supporting Android to swift? Why are there so few swift APIs?

Hi, thanks for your interest in this project. Turf is a work in progress. If you need a particular API, please request it specifically. We also welcome pull requests that port APIs from the JavaScript or Java versions of Turf.

嗨，谢谢您对这个项目的关注。 Turf正在进行中。 如果您需要特定的API，请特别要求。 我们也欢迎从Turf的JavaScript或Java版本移植API的拉取请求。
