### ISSUE TITLE
Is there a way to get the center of the polygon?

### ISSUE THREAD

**Issue by bagusflyer** [mapbox/turf-swift#145]
Is there a way to get the center of the polygon by using `turf-swift`?

**Comment by Udumft** [comment]
Hello, @bagusflyer! Unfortunately there is no API method to do that. But I think it should be as simple as calculating "average" among all of Polygon's coordinates.

**Comment by 1ec5** [comment]
> But I think it should be as simple as calculating "average" among all of Polygon's coordinates.

That’s one kind of center, but it only yields reasonable results for convex polygons.

Turf.js has several center- and centroid-related functions that we could port to Swift:

* [`center`](http://turfjs.org/docs/#center) is similar to the “average” described above.
* [`centerOfMass`](http://turfjs.org/docs/#centerOfMass)
* [`centroid`](http://turfjs.org/docs/#centroid)

The iOS map SDK (until v10) has an `MGLPolyline.coordinate` property that’s very useful for this purpose. Under the hood, it relies on [Polylabel](https://github.com/mapbox/polylabel/), a C++ implementation of the pole-of-inaccessibility algorithm (equivalent to [`ST_MaximumInscribedCircle`](https://postgis.net/docs/ST_MaximumInscribedCircle.html) in PostGIS). There are other centroid algorithms, but the pole of inaccessibility algorithm yields very good results overall.
