### ISSUE TITLE
Conform all geojson related types to Equatable

### ISSUE THREAD

**Issue by klundberg** [mapbox/turf-swift#150]
Hello,

I'm looking to store some decoded geojson values in a struct that is marked equatable. If I use Turf's types for this today, I need to manually implement the `==` operator function, which I can only do by either ignoring the geojson values entirely, or by manually specifying an `==` function for each type I want to store, and all of those types' properties' types as well. If the library could provide these conformances for us, that would be much easier.

I realize that some types' variables aren't able to easily do this, namely properties with a `[String: Any]` dictionary type. There's another library I've been using that I'd like to transition off of here (https://github.com/kiliankoe/GeoJSON) which has solved this by using an `AnyCodable` type that conforms to Equatable, so that the properties dictionary can also be Equatable. Could Turf adopt a similar approach here?

Thanks!

**Comment by 1ec5** [comment]
> using an `AnyCodable` type that conforms to Equatable

AnyCodable comes from the [AnyCodable](https://github.com/flight-school/AnyCodable/) package, which we could adopt as a dependency. Alternatively, we could jettison the GeoJSON types in this library in favor of [GeoJSON](https://github.com/kiliankoe/GeoJSON/). When we originally implemented codable GeoJSON types in #45, we were unaware of any other library that was doing the same thing as elegantly.

We’re on the cusp of a new major version, so it would be an inopportune time to introduce new dependencies. However, neither the AnyCodable library’s Equatable conformance nor the GeoJSON library’s `Feature.Properties` type are very complex; we could easily vendor them into this project without introducing any backwards compatibility or interdependency conflict. Both libraries are MIT-licensed.

As long as `Feature.Properties` is written carefully enough to be a drop-in replacement for Dictionary, we should be able to make the requested changes without breaking backwards compatibility.
