### ISSUE TITLE
Int property of value = 1 converts to bool unexpectedly

### ISSUE THREAD

**Issue by metaine** [mapbox/turf-swift#173]
```
 if let bool = rawValue as? Bool {
            self = .boolean(bool)
   } 
```

**Comment by 1ec5** [comment]
https://github.com/mapbox/turf-swift/blob/436682278bd65a1dbfbad53902af6f4cc0af1a33/Sources/Turf/JSON.swift#L70-L75

**Comment by 1ec5** [comment]
@metaine, can you provide example code that results in the unexpected conversion? I added a unit test in 45213339c62c6afc88c5099c8adf43e03509867d demonstrating that `JSONValue(rawValue:)` keeps Booleans as Booleans and integers as numbers, but maybe you’re running into an issue somewhere else?
