### ISSUE TITLE
Optionally avoid decoding or encoding foreign members

### ISSUE THREAD

**Issue by 1ec5** [mapbox/turf-swift#186]
ForeignMemberContainer’s Codable implementation can be very slow for complex GeoJSON because it needs to iterate over `allKeys` and convert each individual coding key. The Codable implementations of ForeignMemberContainer-containing types should short-circuit foreign member encoding and decoding when the encoder or decoder’s `userInfo` contains a flag suppressing this step.

/ref https://github.com/mapbox/mapbox-directions-swift/pull/669#discussion_r842877486
/cc @mapbox/navigation-ios @macdrevx

**Comment by 1ec5** [comment]
Should we disable foreign member processing by default and make it an opt-in feature? Client code usually knows upfront whether it expects foreign members in a given GeoJSON object. Unfortunately, #175 enabled foreign member processing unconditionally, so making it an opt-out feature now might be considered a backwards-incompatible change in behavior. But if no one is using that functionality yet, maybe it would be a reasonable tradeoff?

/cc @ZiZasaurus @VysotskiVadim

**Comment by VysotskiVadim** [comment]
@1ec5 , what's a use case of using GeoJSON. I didn't find any usages in the context of Android Navigation SDK. In mapbox-java [we don't even mention GeoJSON geometry](https://github.com/mapbox/mapbox-java/blob/main/services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/RouteOptions.java#L1408)
