### ISSUE TITLE
Add property to Point or LineString

### ISSUE THREAD

**Issue by aSeniyants** [mapbox/turf-swift#194]
Hello.
I want parse map.osm to geoJSON with Turf...
And in openstreetmap use tag:
`<tag k="shop" v="convenience"/>`

How can i add this tag in geoJSON file?
Thank you

**Comment by 1ec5** [comment]
Hi, are you trying to convert a file in OpenStreetMap XML format to GeoJSON format? That would be similar to what the [osmtogeojson](https://github.com/tyrasd/osmtogeojson/) library does. That library is written in JavaScript, but you might find it to be a useful model to follow when writing similar code in Swift.

An OSM element would be represented by a Feature, so you can set the key `shop` to the value `convenience` in the feature’s `properties` dictionary.

**Comment by aSeniyants** [comment]
> Hi, are you trying to convert a file in OpenStreetMap XML format to GeoJSON format? That would be similar to what the [osmtogeojson](https://github.com/tyrasd/osmtogeojson/) library does. That library is written in JavaScript, but you might find it to be a useful model to follow when writing similar code in Swift.
> 
> An OSM element would be represented by a Feature, so you can set the key `shop` to the value `convenience` in the feature’s `properties` dictionary.

Thank you for your answer.
Turf work very good, but i understand that i need [osmium](https://osmcode.org/osmium-tool/)
