### ISSUE TITLE
v2.5.0 documentation lacks method signatures

### ISSUE THREAD

**Issue by 1ec5** [mapbox/turf-swift#195]
The published documentation for v2.5.0 lacks method signatures, and anchors to specific sections of the pages are broken. Compare the `LineString.intersection(with:)` documentation between v2.4.0 and v2.5.0:

[<img src="https://user-images.githubusercontent.com/1231218/186295248-49e1ffac-c0de-4f8b-ac41-bd081fc58928.png" width="400" alt="v2.4.0" align="top">](https://mapbox.github.io/turf-swift/2.4.0/Functions.html#/s:4Turf12intersectionySo22CLLocationCoordinate2DVSgAD_ADt_AD_ADttF) [<img src="https://user-images.githubusercontent.com/1231218/186295284-8bd6a46e-2a0a-4641-85d0-5366aea92856.png" width="400" alt="v2.5.0" align="top">](https://mapbox.github.io/turf-swift/2.5.0/Functions.html#/)

This is a symptom of missing USRs. jazzy probably outputs a warning indicating the problem.

/cc @mapbox/navigation-ios

**Comment by azarovalex** [comment]
CI should fail on warnings most probably
