### ISSUE TITLE
Port turf-bbox

### ISSUE THREAD

**Issue by jmkiley** [mapbox/turf-swift#50]
Port [`turf-bbox`](https://github.com/Turfjs/turf/tree/6cec9ad307bcb2f47a0f1ace843b2a0f20692b64/packages/turf-bbox) and [`turf-bbox-polygon`](https://github.com/Turfjs/turf/tree/6cec9ad307bcb2f47a0f1ace843b2a0f20692b64/packages/turf-bbox-polygon) to create a rect containing a polygon.

This will also include [`turf/helpers~validateBbox`](https://github.com/Turfjs/turf/blob/6cec9ad307bcb2f47a0f1ace843b2a0f20692b64/packages/turf-helpers/index.mjs#L672).

This will help with porting both [`turf-boolean-point-in-polygon`](https://github.com/Turfjs/turf/tree/6cec9ad307bcb2f47a0f1ace843b2a0f20692b64/packages/turf-boolean-point-in-polygon) and [`turf-hex-grid`](https://github.com/Turfjs/turf/tree/6cec9ad307bcb2f47a0f1ace843b2a0f20692b64/packages/turf-hex-grid) (#33 ).

**Comment by frederoni** [comment]
This landed in #64
