### ISSUE TITLE
Turf-Swift no longer compiles with Xcode pre-9.3

### ISSUE THREAD

**Issue by samfader** [mapbox/turf-swift#59]
Due to changes around the [Equatable and Hashable protocols](https://github.com/apple/swift-evolution/blob/master/proposals/0185-synthesize-equatable-hashable.md) in Swift 4.1, turf-swift no longer compiles with Xcode pre-9.3.

Options to support older versions of Xcode include bumping the minimum Swift/Xcode versions for Turf-Swift, or adding Swift 4 compatible code for these classes.

**Comment by 1ec5** [comment]
#83 migrated to Swift 5, which has the effect of requiring Xcode 10.2 and above.
