### ISSUE TITLE
Properties inside FeatureCollection should be optional

### ISSUE THREAD

**Issue by Zasuk** [mapbox/turf-swift#60]
Right now the parsing is failing if the feature collection don't have "properties".
i'm using http://geojson.io/ to generate my files.

**Comment by bsudekum** [comment]
Looking at the code, it looks like the properties key is already optional:

https://github.com/mapbox/turf-swift/blob/3b9d54b5de2cbf838ddcdc48f5c930917c2c9aa8/Sources/Turf/FeatureCollection.swift#L8

**Comment by nitaliano** [comment]
@bsudekum I actually just ran into this when it tries to deserialize the json it fails if there is no properties

**Comment by bsudekum** [comment]
👍 , yeah you're both right.

**Comment by nitaliano** [comment]
Submitted a PR for it
