### ISSUE TITLE
GeoJSON object cannot be set programmatically

### ISSUE THREAD

**Issue by appacea** [mapbox/turf-swift#68]
Hi,

Looks like the example from the README is broken. This no longer works:

// Initialize a PointFeature and encode as GeoJSON
let coordinate = CLLocationCoordinate2D(latitude: 0, longitude: 1)
let point = Point(coordinate)
let pointFeature = PointFeature(point)
let data = try! JSONEncoder().encode(pointFeature)
let json = String(data: data, encoding: .utf8)

It seems you can now only create a PointFeature from a JSON file. Is that by design?

Test Specs: 
Turf (0.2.0)
Xcode 9.4.1
Swift 4

**Comment by frederoni** [comment]
Initializer for `PointFeature` is exposed publicly but it hasn't been released yet. You can point your Podfile or Cartfile to master to make use of it. However, the missing initializers for `LineString`,`MultiLineString`, `MultiLineStringFeature`, and `FeatureCollection` is being addressed in #69.
