### ISSUE TITLE
Turf: add polygonToLine

### ISSUE THREAD

**Issue by samfader** [mapbox/turf-swift#81]
This is a feature request to add http://turfjs.org/docs/#polygonToLine to this library. This method converts a Polygon to (Multi)LineString or MultiPolygon to a FeatureCollection of (Multi)LineString.

**Comment by 1ec5** [comment]
These conveniences were removed in #95, possibly unintentionally. We should add them back in for parity with Turf.js.

/cc @Udumft

**Comment by Udumft** [comment]
Do we have requests for other conversion or utility features present in JS?
