### ISSUE TITLE
Could not find module 'Turf' for target

### ISSUE THREAD

**Issue by JyyJDast1** [mapbox/turf-swift#82]
when  I change the debug of "build active architecture only" of "build setting" of my target to NO,it comes out the error : 

/TurfBridgeOC.swift:11:8: Could not find module 'Turf' for target 'armv7-apple-ios'; found: arm64, arm64-apple-ios

why?

**Comment by frederoni** [comment]
How did you integrate turf-swift? CocoaPods, Carthage, or manually? If using package manager, would you mind including a snippet of the setup?

It looks like you built turf-swift for arm64, and your Obj-C targets supports armv7.

**Comment by JyyJDast1** [comment]
> How did you integrate turf-swift? CocoaPods, Carthage, or manually? If using package manager, would you mind including a snippet of the setup?
> 
> It looks like you built turf-swift for arm64, and your Obj-C targets supports armv7.

yeah，I use pods.I try to change turf target to the same building setting, then the error gone~ thanks a lot!
