### ISSUE TITLE
Remove Polyline type alias

### ISSUE THREAD

**Issue by 1ec5** [mapbox/turf-swift#86]
#45 renamed Polyline to LineString, for consistency with GeoJSON terminology, but left Polyline as a type alias to LineString, for consistency with the map SDK. For v1.0, we should remove this type alias outright, because it conflicts with the [Polyline](https://github.com/raphaelmor/Polyline/) library, which is commonly used in conjunction with Turf (for instance, in MapboxDirections.swift). Unfortunately, I think the problem would persist even if we leave in the type alias but mark it unavailable. We’ll just have to document that LineString isn’t a kind of String and is what people want for polyline geometries.

The workaround is currently to `import Polyline` and `import struct Turf.LineString` in any file that needs to work with the two types simultaneously.

/cc @mapbox/navigation-ios @frederoni

**Comment by Udumft** [comment]
Seems to be resolved in [this PR](https://github.com/mapbox/turf-swift/pull/93).
