### ISSUE TITLE
Polygon.contains(_:ignoreBoundary:) returns false for coordinates on boundary coinciding with bounding box

### ISSUE THREAD

**Issue by fphilipe** [mapbox/turf-swift#88]
When specifying `ignoreBoundary: false` in `Polygon.contains(_:ignoreBoundary:)` (the default value), coordinates on the boundary that coincide with the bounding box are incorrectly considered not to be contained.

`Ring.contains(_:ignoreBoundary:)` on the other hand works as expected.

The issue is that the optimization used in `Polygon.contains(_:ignoreBoundary:)` to first do a check whether the point is within the bounding box

https://github.com/mapbox/turf-swift/blob/22246d45d321006b938a2102283efa6911ce1e66/Sources/Turf/Polygon.swift#L73-L76

does not pass on `ignoreBoundary` as `BoundingBox.contains(_:)` doesn't have this parameter:

https://github.com/mapbox/turf-swift/blob/22246d45d321006b938a2102283efa6911ce1e66/Sources/Turf/BoundingBox.swift#L30

The following code shows the problem:

```swift
let center = CLLocationCoordinate2D(latitude:  0, longitude:  0)
let sw     = CLLocationCoordinate2D(latitude: -1, longitude: -1)
let se     = CLLocationCoordinate2D(latitude: -1, longitude:  1)
let ne     = CLLocationCoordinate2D(latitude:  1, longitude:  1)
let nw     = CLLocationCoordinate2D(latitude:  1, longitude: -1)

let coords = [sw, nw, ne, se, sw]

let polygon = Polygon([coords])
let ring = Ring(coordinates: coords)

// Center is contained:

XCTAssertTrue(ring.contains(center))
XCTAssertTrue(polygon.contains(center))

// Corners are not contained when excluding boundary:

XCTAssertFalse(ring.contains(sw, ignoreBoundary: true))
XCTAssertFalse(ring.contains(nw, ignoreBoundary: true))
XCTAssertFalse(ring.contains(ne, ignoreBoundary: true))
XCTAssertFalse(ring.contains(se, ignoreBoundary: true))

XCTAssertFalse(polygon.contains(sw, ignoreBoundary: true))
XCTAssertFalse(polygon.contains(nw, ignoreBoundary: true))
XCTAssertFalse(polygon.contains(ne, ignoreBoundary: true))
XCTAssertFalse(polygon.contains(se, ignoreBoundary: true))

// Corners are contained when including boundary:

XCTAssertTrue(ring.contains(sw, ignoreBoundary: false))
XCTAssertTrue(ring.contains(nw, ignoreBoundary: false))
XCTAssertTrue(ring.contains(ne, ignoreBoundary: false))
XCTAssertTrue(ring.contains(se, ignoreBoundary: false))

XCTAssertTrue(polygon.contains(sw, ignoreBoundary: false)) // XCTAssertTrue failed
XCTAssertTrue(polygon.contains(nw, ignoreBoundary: false)) // XCTAssertTrue failed
XCTAssertTrue(polygon.contains(ne, ignoreBoundary: false)) // XCTAssertTrue failed
XCTAssertTrue(polygon.contains(se, ignoreBoundary: false)) // XCTAssertTrue failed
```

I'd suggest to address this in the following way:

- Change `BoundingBox.contains(_:)` to `BoundingBox.contains(_:ignoreBoundary:)` with a default of `true` to preserve the current behavior.
- Optionally, move the bounding box optimization from `Polygon` to `Ring` in order for `Ring` to benefit from this optimization as well (`Polygon` would still benefit indirectly from this optimization).

I'd be happy to make a PR if you agree on the suggested approach.

**Comment by 1ec5** [comment]
Sounds good to me!
