### ISSUE TITLE
Sane JSON Representations

### ISSUE THREAD

**Issue by JThramer** [mapbox/turf-swift#94]
There are places in `turf-swift` where we currently represent a JSON object with `[String:AnyJSONType]` as opposed to the more common `[String:Any]` regularly found in iOS frameworks.

As mentioned [elsewhere](https://github.com/mapbox/turf-swift/pull/93#discussion_r386712617), `[AnyJSONType]` isn't really worth the hassle of keeping around, since you still have to type-cast for the value at the point-of-use.

https://github.com/mapbox/turf-swift/blob/093d9cb4fce73b14f4f9ceb5766a313e4d8972be/Sources/Turf/Codable.swift#L23-L70

Let's get a PR going where we remove the replace the bespoke representation with a standard one.

/cc @mapbox/navigation-ios

**Comment by 1ec5** [comment]
Any type alias should be for `[String: Any?]`, not `[String: Any]`, because `null` is a valid JSON value. `[String: Any]` may be more convenient in some cases where you know you aren’t dealing with optionals, but that kind of shortcut doesn’t belong in a public API.

**Comment by frederoni** [comment]
Also `Any` is not Codable so you need a custom type for the encoder/decoder to do its thing.
Perhaps just renaming it to `AnyGeoJSONCompatibleType` would make things clearer.

**Comment by 1ec5** [comment]
In that case, we can encode `[String: JSONType?]` and rely on the existing JSONType conformances, allowing the Codable system to implement AnyJSONType’s functionality for us:

https://github.com/mapbox/turf-swift/blob/093d9cb4fce73b14f4f9ceb5766a313e4d8972be/Sources/Turf/Codable.swift#L10-L21

**Comment by Udumft** [comment]
`JSONType` is a protocol, so it' wont provide conformance to `Decodable` itself. 
As a solution, I suggest implementing a `decode` specialization to custom handle decoding `[String: Any?]`. This will remove the original type casting issue.
